### ISSUE TITLE
Enable for puppet

### ISSUE THREAD

**Issue by misaflo** [noprompt/vim-yardoc#8]
Hello,

Can you enable YARD tags syntax highlighting for puppet files (.pp)?

Puppet also use YARD tags (https://puppet.com/docs/puppet/6.18/puppet_strings_style.html#example-class).

**Comment by noprompt** [comment]
@misaflo Yes. I'm fine with that. Are you able to submit a patch?

**Comment by misaflo** [comment]
I tried to combine vim-yardoc with [vim-puppet](https://github.com/rodjek/vim-puppet), but without success.

**Comment by misaflo** [comment]
Issue also reported on [vim-puppet](https://github.com/rodjek/vim-puppet/issues/125).
